### ISSUE TITLE
Port over `PolyfillExecutionContext`

### ISSUE THREAD

**Issue by djspiewak** [scala-js/scala-js-macrotask-executor#2]
I created a stub but we should probably name it something less redundant.

**Comment by armanbilge** [comment]
I really think we should keep the name as `MacrotaskExecutor`. It _is_ redundant to the package name, but after it's imported the redundancy vanishes and I think it is exactly the right name (anything else would only become more confusing/ambiguous). Ideally, the package name would be less redundant (hypothetically, what if this project was just `scala-js-executors` and we had an `executors` package with hypothetical other useful executors in here.)
