### ISSUE TITLE
Fix the polyfill for JSDOM

### ISSUE THREAD

**Issue by djspiewak** [scala-js/scala-js-macrotask-executor#9]
Yeah it actually just doesn't work:

```
[info] org.scalajs.macrotaskexecutor.MacrotaskExecutorSuite:
[info]   + sequence a series of 10,000 recursive executions without clamping 25.78s
[info]   + preserve fairness with setTimeout 0.11s
[info]   + execute a bunch of stuff in 'parallel' and ensure it all runs 13.14s
```

"without clamping"

If we can fix this, we can uncomment the assertion which ensures that we're actually not being clamped.

**Comment by armanbilge** [comment]
Update on this: I tried 2 things.
1. Fixing the `postMessage` detection stuff, since `postMessage` does appear to be implemented in JSOM. This gets us:
  ```
/workspace/scala-js-macrotask-executor/node_modules/jsdom/lib/jsdom/living/helpers/events.js:15
  const event = createAnEvent(e, target._globalObject, eventInterface, attributes);
                                        ^

TypeError: Cannot read property '_globalObject' of undefined
    at fireAnEvent (/workspace/scala-js-macrotask-executor/node_modules/jsdom/lib/jsdom/living/helpers/events.js:15:41)
    at Timeout._onTimeout (/workspace/scala-js-macrotask-executor/node_modules/jsdom/lib/jsdom/living/post-message.js:36:7)
  ```
2. Implementing the IE polyfill which relies on `<script>`. This doesn't work because of JSDOM security measures:
    > The jsdom sandbox is not foolproof, and code running inside the DOM's <script>s can, if it tries hard enough, get access to the Node.js environment, and thus to your machine. As such, the ability to execute scripts embedded in the HTML is disabled by default

    https://github.com/jsdom/jsdom#executing-scripts

**Comment by armanbilge** [comment]
Update on 2: it seems the JSDOM env for JS already disables that security measure. So, my implementation of the polyfill is broken then or something else weird is going on.

**Comment by armanbilge** [comment]
Ok, here's another fun experiment. Turns out that `setImmediate` _is_ defined on JSDOM, just our conditional check is broken for whatever reason. If we hardcode it:
```diff
diff --git a/core/src/main/scala/org/scalajs/macrotaskexecutor/MacrotaskExecutor.scala b/core/src/main/scala/org/scalajs/macrotaskexecutor/MacrotaskExecutor.scala
index 33ac1b4..6be8ab8 100644
--- a/core/src/main/scala/org/scalajs/macrotaskexecutor/MacrotaskExecutor.scala
+++ b/core/src/main/scala/org/scalajs/macrotaskexecutor/MacrotaskExecutor.scala
@@ -35,7 +35,7 @@ object MacrotaskExecutor extends ExecutionContextExecutor {
     cause.printStackTrace()
 
   private[this] val setImmediate: (() => Unit) => Unit = {
-    if (js.typeOf(js.Dynamic.global.setImmediate) == Undefined) {
+    if (false || js.typeOf(js.Dynamic.global.setImmediate) == Undefined) {
       var nextHandle = 1
       val tasksByHandle = mutable.Map[Int, () => Unit]()
       var currentlyRunningATask = false

```

It runs, but it's still clamped 😠

**Comment by armanbilge** [comment]
Also worth nothing that the `postMessage` implementation in JSDOM itself uses `setTimeout`:
https://github.com/jsdom/jsdom/blob/master/lib/jsdom/living/post-message.js#L35-L37

**Comment by djspiewak** [comment]
> Also worth nothing that the postMessage implementation in JSDOM itself uses setTimeout:

Wtf… Seriously?

**Comment by djspiewak** [comment]
How is it that we don't have access to `setImmediate` in jsdom? It's a node environment, and they seem to use it internally: https://github.com/jsdom/jsdom/blob/9dae17bf0ad09042cfccd82e6a9d06d3a615d9f4/lib/jsdom/living/xhr/xhr-utils.js#L410

**Comment by armanbilge** [comment]
> How is it that we don't have access to setImmediate in jsdom

IDK, they do some sandboxing to make the global scope behave like a browser scope.

However, the README alludes to someway to access Node:
> The jsdom sandbox is not foolproof, and code running inside the DOM's <script>s can, if it tries hard enough, get access to the Node.js environment, and thus to your machine.

I'm just not clever enough to see _how_.

**Comment by djspiewak** [comment]
> if it tries hard enough

![image](https://user-images.githubusercontent.com/752/132283126-aa11b4f5-6ab8-4e4c-8d90-f44478f4d166.png)

JK. Maybe we should just give up on jsdom. The polyfill is *functional* on that platform, it's just slow.

**Comment by armanbilge** [comment]
🙃 Let's keep this issue and maybe mark it help wanted? Who knows, inspiration may strike.

In the meantime, I can disable the clamping test for only JSDOM so we can run it in the other environments.

**Comment by djspiewak** [comment]
> In the meantime, I can disable the clamping test for only JSDOM so we can run it in the other environments.

I think that's the right approach.
